# Generated by Django 3.2.9 on 2021-11-26 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_year'),
        ('movie', '0002_auto_20211125_1048'),
    ]

    operations = [
    ]
